name: sgr
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - scipy
  - hyperopt
  - jupyter
  - lightgbm # for hyperopt
  - lxml
  - numpy
  - openpyxl
  - pandas
  - pyyaml
  - requests
  - rich
  - scikit-learn
  - shap
  - tqdm
  - pip
  - pip:
    - igdb-api-v4
    - sentence-transformers
    - xgboost
