name: sgr
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - jupyter
  - lxml
  - numpy
  - pandas
  - requests
  - rich
  - scikit-learn
  - shap
  - openpyxl
  - pip
  - pip:
    - sentence-transformers
    - xgboost