name: sgr
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - jupyter
  - lxml
  - numpy
  - openpyxl
  - pandas
  - pyyaml
  - requests
  - rich
  - scikit-learn
  - shap
  - xgboost
  - pip
  - pip:
    - sentence-transformers
